# Get python docker image version 3.7
FROM python:3.7

# Create working directory variable
ENV WORKDIR=/submissions-pipeline

# Set up volume directory in docker
VOLUME ${WORKDIR}

# Set up working directory in docker
WORKDIR ${WORKDIR}

# Define a system argument
ARG DEBIAN_FRONTEND=noninteractive

# Install system libraries of general use and python v3.5 and odbc connector
RUN apt-get update && apt-get install -y --no-install-recommends build-essential \
    dos2unix

# Copy python requirements file to docker images
COPY requirements.txt /opt/public-repository-submissions/requirements.txt

# Install python requirements
RUN pip install --no-cache-dir -r /opt/public-repository-submissions/requirements.txt

# Make the app available at port 3838
EXPOSE 3838

# Create a data directory to store metadata and fasta files
RUN mkdir /opt/public-repository-submissions/data

# Create a template directory to store sample config and metadata worksheet
RUN mkdir /opt/public-repository-submissions/template

# Create a test_input directory to testing files
RUN mkdir /opt/public-repository-submissions/test_input

# Copy config files to docker images
COPY config_files/default_config.yaml /opt/public-repository-submissions/config_files/default_config.yaml
COPY config_files/required_columns.yaml /opt/public-repository-submissions/config_files/required_columns.yaml

# Copy template files to docker images
COPY config_files/default_config.yaml /opt/public-repository-submissions/template/default_config_template.yaml
COPY config_files/required_columns.yaml /opt/public-repository-submissions/template/required_columns_template.yaml
COPY test_input/test_metadata.tsv /opt/public-repository-submissions/template/metadata_template.tsv

# Copy submission.xml to pipeline in order to run test_bioproject function
COPY test_input/submission.xml /opt/public-repository-submissions/test_input/submission.xml

# Copy additional python scripts to docker images
COPY singularity/extract_config.py /opt/public-repository-submissions/extract_config.py
COPY singularity/extract_metadata.py /opt/public-repository-submissions/extract_metadata.py
COPY singularity/update_upload_log.py /opt/public-repository-submissions/update_upload_log.py
COPY singularity/check.py /opt/public-repository-submissions/check.py
COPY singularity/retrieve.py /opt/public-repository-submissions/retrieve.py

# Copy additional bash scripts to docker images
COPY singularity/save_config.sh /opt/public-repository-submissions/save_config.sh
COPY singularity/public-repository-submissions.sh /opt/public-repository-submissions/public-repository-submissions.sh

# Copy pipeline scripts to docker images
COPY biosample_sra_submission.py /opt/public-repository-submissions/biosample_sra_submission.py
COPY genbank_submission.py /opt/public-repository-submissions/genbank_submission.py
COPY gisaid_submission.py /opt/public-repository-submissions/gisaid_submission.py
COPY gisaid_uploader.py /opt/public-repository-submissions/gisaid_uploader.py
COPY seqsender.py /opt/public-repository-submissions/seqsender.py
COPY submission_preparation.py /opt/public-repository-submissions/submission_preparation.py

# Convert public-repository-submissions.sh from Windows style line endings to Unix-like control characters
RUN dos2unix /opt/public-repository-submissions/public-repository-submissions.sh

# Allow permission to excute the bash scripts
RUN chmod a+x /opt/public-repository-submissions/public-repository-submissions.sh

# Allow permission to read, write, and execute files in /opt/public-repository-submissions directory
RUN chmod -R a+rwx /opt/public-repository-submissions

# Allow permission to read, write, and execute files in submissions-pipeline directory
RUN chmod -R a+rwx ${WORKDIR}

# Clean up
RUN apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# Execute the pipeline 
ENTRYPOINT ["/bin/bash", "/opt/public-repository-submissions/public-repository-submissions.sh"]








