version: "3.9"

x-data-volumes:
  &data-volume
  type: bind
  source: $HOME
  target: /data

services:
  seqsender:
    container_name: seqsender
    image: seqsender:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - micromamba_version=1.5.3
    restart: always
    volumes:
      - *data-volume
    command: tail -f /dev/null
