version: "3.9"

x-seqsender-git-version:
  &seqsender-git-version  
  https://github.com/CDCgov/seqsender.git#dev

x-data-volumes:
  &data-volume
  type: bind
  source: /path/to/data
  target: /data

services:
  seqsender: 
    container_name: seqsender
    image: seqsender
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - *data-volume
    command: tail -f /dev/null 
