version: "3.9"

x-data-volumes:
  &data-volume
  type: bind
  source: $HOME/Github/Testings/seqsender
  target: /data

services:
  seqsender: 
    container_name: seqsender
    image: cdcgov/seqsender:latest
    restart: always
    volumes: 
      - *data-volume
    command: tail -f /dev/null 
