---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(message=FALSE, comment="#>", fig.width=8, fig.height=8, fig.align="center")
```

## SeqSender

**SeqSender** is used to generate the files necessary to upload via FTP to NCBI's databases **Genbank**, **BioSample**, and **SRA**, as well as, **GISAID**. The pipeline then automatically performs the sequential upload to these databases to ensure proper linkage of data. The pipeline is dynamic in that the user creates a config file to select which databases they would like to upload and allows for any possible metadata fields by using a YAML to pair the database's metadata fields which your personal metadata field columns. This pipeline is currently tested with uploading SARS-COV2 data but the dynamic nature of this pipeline will allow for other organism's in future updates.

## Dockerize SeqSender Pipeline

### Requirements

- Docker version >= 18
- Git version >= 2.21.0

### (1) Clone this respitory

```
git clone https://git.biotech.cdc.gov/snu3/seqsender.git
``` 

### (2) CD to `seqsender` folder where `Dockerfile` file is stored and build the docker image. NOTE: `Dockerfile` contains a list of instructions and steps of how to build and run the pipeline.

```
docker build -t seqsender:1.0.0 .
```

**-t**: add a tag to an image such as the version of the application, *seqsender:1.0.0* or *seqsender:latest*

_The image took < 20 seconds to build_

### (3) After the build is completed, you can check if the image is built successfully

```
docker images

REPOSITORY    TAG       IMAGE ID        CREATED        SIZE
seqsender     1.0.0     d9e2578d2211    2 weeks ago    1.07GB
```

### (4) See a list of commands in `seqsender` 

```    
docker run -v [host_dir]:[container_dir] -it seqsender:1.0.0 --help
```

**-t**: allocate a pseudo-tty <br>
**-i**: keep STDIN open even if not attached  <br>
**-v**: mount code base and data files from the host directory to container directory **<host_dir>:<container_dir>**.

For more information about the Docker syntax, see [Docker run reference](https://docs.docker.com/engine/reference/run/)

### (5) Run `seqsender` image using provided datasets

In __seqsender/test_input__ and __seqsender/config_files__ subfolders, there are files which can be used to run the `seqsender` pipeline. Change _**/path/to/seqsender**_ path to your local _**seqsender**_ directory below.

```
docker run -v /path/to/seqsender/:/submissions-pipeline/ -it seqsender:1.0.0 seqsender prep --unique_name test_submission --config config_files/test_config.yaml --metadata test_input/test_metadata.tsv --fasta test_input/test_fasta.fasta --test
``` 

In this example, we are mapping **/path/to/seqsender** directory in the host machine to **submissions-pipeline** directory inside the container machine. By exposing the host directory to docker container, docker would be able to access data files within that mounted directory and use it to run the submission pipeline. The code above runs the **prep** command from `seqsender:1.0.0` image.

## Convert Docker Images to Singularity Images and use it on any Linux machines

### Requirements

- singularity version >= 2.1 (does not need to install **Docker** on your machine)

In this example, we will use the existing **"seqsender:1.0.0"** docker image that we created above and convert it to singularity for use on a Linux VM.

__1.__ Find the Docker image ID

```
docker images

REPOSITORY    TAG       IMAGE ID        CREATED        SIZE
seqsender     1.0.0     d9e2578d2211    2 weeks ago    1.07GB
```

__2.__ Create a tarball of the Docker image.

For example, **seqsender:1.0.0** has an IMAGE ID of **d9e2578d2211**, so we can create a tarball using the **docker save** command.

```
docker save d9e2578d2211 -o seqsender-v1.0.0.tar 
```

To explore the contents of the tarball:

```
tar tvf seqsender-v1.0.0.tar
```

_Note: The **"tarball"** is a Docker-format image comprised of multiple layers along with metadata in a JSON manifest._

__3.__ Copy the tarball to a remote CentOS VM using any File Transfer Protocols (**scp** was used here)

```
scp seqsender-v1.0.0.tar remote_user@remote_server_ip:<remote_home_directory>
```

__4.__ SSH to your remote server

```
ssh remote_user@remote_server_ip
```

__5.__ Check if singularity is installed on the server

```
singularity --version

singularity version 3.8.7-1.el8
```

If singularity is not installed, check out [this installation article](https://sylabs.io/guides/3.0/user-guide/installation.html)

__6.__ Convert the tarball to a Singularity image. Change **/path/to/seqsender-v1.0.0.tar** to the path of where the tarball is stored on the VM

```
singularity build seqsender-v1.0.0.sif docker-archive:///path/to/seqsender-v1.0.0.tar 
```

_Note: The **docker** part of the URI has been appended by **archive**. This ensures Singularity seek a Docker-format image archive stored locally as **seqsender-v1.0.0.tar** to boostrap the conversion process to SIF, as opposed to attempting to retrieve an image remotely hosted via **Docker Hub**._

**Important Note**: By default, Singularity will create a set of folders in your **$HOME** directory for docker layers, Cloud library images, and metadata, respectively. If you want to cache in a different directory, set **SINGULARITY_CACHEDIR** to the desired path. By using the **-E** option with the **sudo** command, **SINGULARITY_CACHEDIR** will be passed along to root's environment and respected during the build. Remember that when you run commands as **root** images will be cached in root's home at **/root** and not your user's home. See [singularity build](https://sylabs.io/guides/3.5/user-guide/cli/singularity_build.html) for more details.

__7.__ To see a list of commands in `seqsender-v1.0.0` singularity image

```
singularity run /path/to/seqsender-v1.0.0.sif --help
```

*Note: Change __/path/to/seqsender-v1.0.0.sif__ to the path of where __seqsender-v1.0.0.sif__ is stored on your machine*


__8.__ To run `seqsender` singularity image using provided datasets. Clone this repository on your remote server

```
git clone https://github.com/CDCgov/seqsender.git
``` 

__9.__ CD to `seqsender` directory where all of the data files are stored


__10.__ Run **"seqsender-v1.0.0"** Singularity image using provided datasets stored in **seqsender/config_files** and **seqsender/test_input** subfolders

```
singularity run --writable-tmpfs /path/to/seqsender-v1.0.0.sif seqsender prep --unique_name test_submission --config config_files/test_config.yaml --metadata test_input/test_metadata.tsv --fasta test_input/test_fasta.fasta --test
```

**--writable-tmpfs**: this stores all changes in an in-memory temporary filesystem which is discarded as soon as the container finishes executing <br>

__Note:__ Change __/path/to/seqsender-v1.0.0.sif__ to the path of where __seqsender-v1.0.0.sif__ is stored on your machine. The code above runs the **prep** command from the `seqsender-v1.0.0` program.

<br>

Any questions or issues? Please report them on our gitlab issues

<br>









