from shiny import App, Inputs, Outputs, Session, render, req, ui, reactive

about_body = [
    ui.h2("About"),
    ui.hr(),
    ui.p("SeqSender is a ", ui.strong("Python"), " program developed to aid the process of submitting genomic samples to public repositories. ",
        "SeqSender ", ui.strong("simplifies"), " the submission process by creating all the necessary submission files for multiple databases from a single metadata file and fasta file. ",
        "Based on the organism and database selection, SeqSender also ", ui.strong("validates"), " that the metadata your submitting meets the requirements of the database to preemptively catch submission errors. ",
        "The tool can also be used to ", ui.strong("submit"), " your samples to each database while also linking the samples between the databases. "),
    ui.p("SeqSender currently supports the databases from NCBI: ", ui.strong("BioSample, "), ui.strong("SRA, "),
        " and ", ui.strong("GenBank "), " and from GISAID: ", ui.strong("EpiFlu, "), ui.strong("EpiCoV, "), ui.strong("EpiPox, "), ui.strong("EpiArbo, "), " and ", ui.strong("EpiRSV"), "."),
    ui.h2("Available Databases"),
    ui.hr(),
    ui.h4("NCBI (National Center for Biotechnology Information)"),
    ui.a(ui.h6("BioProject"), href="https://www.ncbi.nlm.nih.gov/bioproject/"),
    ui.tags.ul(
        ui.p("Is a collection of biological data that is tied to a research project. ",
            "Used to collate your genomic sample data together across multiple databases. ",
            "A BioProject provides a centralized location to identify/connect/share/describe the samples you are submitting to NCBI. ",
            "A BioProject is ", ui.strong("required"), " if you're submitting to certain NCBI databases: ", ui.strong("Sequence Read Archive (SRA), Whole Genome Shotgun (WGS), "), "and ", ui.strong("Transcriptome Shotgun Assembly (TSA)"), ".",
            ),
    ),
    ui.a(ui.h6("Sequence Read Archive (SRA)"), href="https://www.ncbi.nlm.nih.gov/sra"),
    ui.tags.ul(
        ui.p("Is a database of high-throughput raw sequencing data and alignment information. ",
            "The purpose of the database is to support reproducibility to faciliate new discoveries through data analysis. ",
            "The SRA database is part of the ", ui.strong("International Nucleotide Sequence Database Collaboration (INSDC)"), ", which is a joint effort between SRA, European Bioinformatics Institute (EBI), and the DNA Database of Japan (DDBJ) where data submitted to one is shared among them all. ",
            "The database accepts submissions for all organisms, metagenomic, clinical studies, and environmental surveys. ",
            "If your data contains human subjects/metagenomes, you should determine if your data is appropriate for public release, if not you might consider the NIH controlled access via dbGaP (the database of Genotypes and Phenotypes) instead. ",
        ),
        ui.p("SeqSender provides two options for uploading data to SRA, supports multiple files per sample, and supports all of the file type options that SRA supports which includes: BAM, SFF, HDF5, and FASTQ. ",
            "Its easy to add your raw reads files when using SeqSender; using the metadata file in your SeqSender submission, just add the filepath('s) for each sample. ",
            "For more SeqSender information, refer to the tab: ", ui.strong("My First Submission"), ", to learn more about the SRA submission options or to the tab: ", ui.strong("Setup Wizard"), ", to learn about the requirements for submitting to SRA. ",
        ),
    ),
    ui.a(ui.h6("BioSample"), href="https://www.ncbi.nlm.nih.gov/biosample/"),
    ui.tags.ul(
        ui.p("Is a database for storing descriptive information/metadata about biological samples you are submitting to other NCBI databases. ",
            "BioSample provides broad categories for sample/study types called ", ui.a(ui.strong("Packages"), href="https://www.ncbi.nlm.nih.gov/biosample/docs/packages/"), " which determine the metadata submission criteria. ",
            "Including a BioSample submission with your data is a good way to provide revelant information regarding the individual location/organism your sample was collected from. "
        ),
        ui.p("SeqSender supports and validates metadata for all current BioSample Packages. ",
            "Place the chosen BioSample Package name inside your config file. ",
            "For more information refer to the tab ", ui.strong("Setup Wizard"), ", to select the available BioSample Packages and to get the subsequent required metadata. ",
        ),
    ),
    ui.a(ui.h6("GenBank"), href="https://www.ncbi.nlm.nih.gov/genbank/"),
    ui.tags.ul(
        ui.p("Is a database for storing assembled nucleotide sequences and annotations. ",
            "Each sample submitted will be annotated to include gene structure, coding regions, and other function elements related to your specimen. ",
            "Samples uploaded to GenBank are also subject to meeting specific data integrity and quality requirements before they are accepted to GenBank. ",
            ),
        ui.p("SeqSender offers two methods for submitting data to GenBank. ",
             "For Influenza Virus and COVID-19, SeqSender can upload your data via FTP, check submission status, and retrieve your GenBank accessions. ",
             "For all other viruses, GenBank submissions will be made using ", ui.a(ui.strong("table2asn"), href="https://www.ncbi.nlm.nih.gov/genbank/table2asn/"), ". ",
             "The submission can then be manually uploaded to GenBank via NCBI's ", ui.a(ui.strong("submission portal"), href="https://submit.ncbi.nlm.nih.gov/"), " or it can automatically email the submission to GenBank and CC you on it."
            ),
    ),
    ui.a(ui.h4("GISAID (Global Initiative on Sharing All Influenza Data)"), href="https://gisaid.org/"),
    ui.tags.ul(
        ui.layout_column_wrap(
            ui.tags.li(ui.strong("EpiFlu: "), "Influenza Virus"),
            ui.tags.li(ui.strong("EpiCoV: "), "COVID-19"),
            ui.tags.li(ui.strong("EpiPox: "), "Mpox"),
            ui.tags.li(ui.strong("EpiRSV: "), "Respiratory Syncytial Virus"),
            ui.tags.li(ui.strong("EpiArbo: "), "Arbovirus"),
            width=1/2,
            height=50,
            height_mobile=100,
            style="padding-left:5%",
        ),
        ui.p("Is a international data-sharing platform created to rapidly share genomic data for the organisms listed above. ",
             "GISAID purpose is to provide public access for the supported organisms to encourage collaboration while ensuring proper crediting and property rights of the data being submitted. ",
             "Users who wish to upload and access data stored on GISAID must abide by their data-sharing agreements. ",
        ),
        ui.p("SeqSender provides two methods for submitting data to GISAID. ",
             "Users can download the GISAID CLI for the database they wish to upload to and add it to SeqSender, which will enable SeqSender to automatically upload your GISAID samples, link them to GenBank samples, and retrieve the accessions for the samples. ",
             "If you do not wish to add the GISAID CLI to SeqSender, it can still generate and validate the files needed to manually upload your submission to GISAID via their ", ui.a(ui.strong("web portal"), href="https://www.epicov.org/epi3/frontend#54b33f"), ".",
        ),
    ),
]
