from pandera import DataFrameSchema, Column, Check, Index, MultiIndex

schema = DataFrameSchema(
	columns={
		"((?:cmt-StructuredComment)(?:Prefix|Suffix))": Column(
			dtype="object",
			checks=[
				Check.str_length(max_value=50),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			regex=True,
			default="Assembly-Data",
			description="Structured comment keyword. For FLU use \"FluData\", HIV use \"HIV-DataBaseData\", and for COV and other organisms use \"Assembly-Data\".",
			title="Structured Comment Prefix and Suffix",
		),
		"cmt-Assembly-Method": Column(
			dtype="object",
			checks=[
				Check.str_length(max_value=50),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Structured comment keyword. For FLU use \"FluData\", HIV use \"HIV-DataBaseData\", and for COV and other organisms use \"Assembly-Data\".",
			title="Structured Comment Prefix and Suffix",
		),
		"cmt-type": Column(
			dtype="object",
			checks=[
				Check.str_length(max_value=50),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Influenza type of sample.",
			title="Influenza Type",
		),
		"cmt-segment_name": Column(
			dtype="object",
			checks=[
				Check.str_length(max_value=50),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Influenza genome segment of sample",
			title="Segment Name",
		),
		"cmt-host_age": Column(
			dtype="object",
			checks=[
				Check.str_length(max_value=50),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Age of host sample acquired from.",
			title="Host Age",
		),
		"cmt-host_gender": Column(
			dtype="object",
			checks=[
				Check.str_length(max_value=50),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Gender of host sample acquired from.",
			title="Host Gender",
		),
		"cmt-passage": Column(
			dtype="object",
			checks=[
				Check.str_length(max_value=50),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Original or subcultured?",
			title="Passage",
		),
		"cmt-location": Column(
			dtype="object",
			checks=[
				Check.str_length(max_value=50),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="<Country name> / <state or providence>",
			title="Location",
		),
		"cmt-lineage": Column(
			dtype="object",
			checks=[
				Check.str_length(max_value=50),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Genomic lineage of sample.",
			title="Lineage",
		),
		"cmt-resist_to_oseltamivir": Column(
			dtype="object",
			checks=[
				Check.str_length(max_value=50),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Is it resistant to Oseltamivir?",
			title="Resistance to Oseltamivir",
		),
		"cmt-resist_to_zanamvir": Column(
			dtype="object",
			checks=[
				Check.str_length(max_value=50),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Is it resistant to Zanamvir?",
			title="Resistance to Zanamvir",
		),
		"cmt-specimen_id": Column(
			dtype="object",
			checks=[
				Check.str_length(max_value=50),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Specimen ID.",
			title="Specimen ID.",
		),
		"cmt-sender_lab": Column(
			dtype="object",
			checks=[
				Check.str_length(max_value=50),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Lab that provided sample.",
			title="Sender Lab",
		),
		"cmt-seqlab_sample_id": Column(
			dtype="object",
			checks=[
				Check.str_length(max_value=50),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Sample ID from sequencing lab.",
			title="Sequence Lab Sample ID",
		),
	},
     checks=None,
     index=None,
     coerce=False,
     strict="filter",
     name="genbank_cmt_schema",
     ordered=False,
     unique=None,
     report_duplicates="all",
     unique_column_names=True,
     add_missing_columns=False,
     title="seqsender genbank comment file schema",
     description="Schema validation for GenBank database comment file.",
)
