Submission:
  Description:
    Title: test_biosample_flu_submission
    Comment: This is a test submission
    Organization:
      '@role': owner
      '@type': institute
      Name: Institute Name
      Contact:
        '@email': email@myemail.com
        Name:
          First: Jane
          Last: Doe
    Hold:
      release_date: "2017-01-01"
  Action:
    AddFiles:
      '@target_db': GenBank
      File:
        '@file_path': 230627_helix_primary.zip
        DataType: genbank-submission-package
      Attribute:
      - '#text': BankIt_SARSCoV2_api
        '@name': wizard
      - '#text': 'yes'
        '@name': auto_remove_failed_seqs
      Identifier:
        SPUID:
          '#text': 230627_helix_primary
          '@spuid_namespace': ncbi-sarscov2-genbank