COV:
  BioSample:
  - spuid*
  - spuid_namespace***
  - description_title***
  - organism_name***
  - bioproject***
  - bs-isolate***
  - bs-collected_by***
  - bs-collection_date***
  - bs-host***
  - bs-host_disease***
  - bs-isolation_source***
  - bs-geo_loc_name***
  BioSample_SRA:
  - spuid*
  - spuid_namespace***
  - description_title***
  - organism_name***
  - bioproject***
  - file_location***
  - file_path***
  - datatype***
  - bs-isolate***
  - bs-collected_by***
  - bs-collection_date***
  - bs-host***
  - bs-host_disease***
  - bs-isolation_source***
  - bs-geo_loc_name***
  - sra-instrument_model***
  - sra-library_source***
  - sra-library_layout***
  - sra-library_name***
  - sra-library_strategy***
  - sra-library_selection***
  - sra-library_construction_protocol***
  GISAID:
  - submitter
  - fn
  - covv_virus_name*
  - covv_type***
  - covv_passage**
  - covv_collection_date***
  - covv_location***
  - covv_host**
  - covv_gender**
  - covv_patient_age**
  - covv_patient_status**
  - covv_seq_technology**
  - covv_orig_lab***
  - covv_orig_lab_addr***
  - covv_subm_lab***
  - covv_subm_lab_addr***
  - covv_authors***
  Genbank:
  - Sequence_ID*
  - src-organism***
  - src-isolate***
  - src-collection_date***
  - src-country***
  - src-host***
  - src-isolation_source***
  SRA:
  - spuid*
  - spuid_namespace***
  - bioproject***
  - file_location***
  - file_path***
  - datatype***
  - sra-instrument_model***
  - sra-library_name***
  - sra-library_strategy***
  - sra-library_source***
  - sra-library_selection***
  - sra-library_layout***
  - sra-library_construction_protocol***
FLU:
  BioSample:
  - spuid*
  - spuid_namespace***
  - description_title***
  - organism_name***
  - bioproject***
  - bs-strain***
  - bs-collected_by***
  - bs-collection_date***
  - bs-host***
  - bs-host_disease***
  - bs-isolation_source***
  - bs-geo_loc_name***
  BioSample_SRA:
  - spuid*
  - spuid_namespace***
  - description_title***
  - organism_name***
  - bioproject***
  - file_location***
  - file_path***
  - datatype***
  - bs-strain***
  - bs-collected_by*** 
  - bs-collection_date***
  - bs-host***
  - bs-host_disease***
  - bs-isolation_source***
  - bs-geo_loc_name***
  - sra-instrument_model***
  - sra-library_source***
  - sra-library_layout***
  - sra-library_name***
  - sra-library_strategy***
  - sra-library_selection***
  - sra-library_construction_protocol***
  GISAID:
  - Isolate_Id
  - Segment_Ids
  - Isolate_Name***
  - Subtype***
  - Location***
  - Host***
  - Seq_Id (HA)*
  - Seq_Id (NA)*
  - Seq_Id (PB1)*
  - Seq_Id (PB2)*
  - Seq_Id (PA)*
  - Seq_Id (MP)*
  - Seq_Id (NS)*
  - Seq_Id (NP)*
  - Seq_Id (HE)*
  - Seq_Id (P3)* 
  - Originating_Lab_Id***
  - Collection_Date***
  Genbank:
  - Sequence_ID*
  - src-organism***
  - src-strain***
  - src-collection_date***
  - src-country***
  - src-host***
  - src-serotype***
  - src-isolation_source***
  SRA:
  - spuid*
  - spuid_namespace***
  - bioproject***
  - file_location***
  - file_path***
  - datatype***
  - sra-instrument_model***
  - sra-library_name***
  - sra-library_strategy***
  - sra-library_source***
  - sra-library_selection***
  - sra-library_layout***
  - sra-library_construction_protocol***
