EpiFlu:
  Adamantanes_Resistance_geno: '"Unknown", "Resistant", "Sensitive", "Inconclusive" '
  Adamantanes_Resistance_pheno: '"Unknown", "Resistant", "Sensitive", "Inconclusive" '
  Antigen_Character: e.g. 'A/Brisbane/10/2007 like'
  Authors: "Citing authors.\n\tList of last, first seperated by ;\n\tE.g.: 'Smith,\
    \ J.; Jones, D.; Humphries, R.;'"
  Collection_Date**: "Mandatory.\n\tAt the command line, the default for '--dateformat'\
    \ correspond to delimited date formats\n    consistent with YYYYMMDD. \n    For\
    \ example:\n      - YYYYMMDD corresponds to YYYY-MM-DD, YYYY/MM/DD or YYYY.MM.DD,\n\
    \      - YYYYDDMM corresponds to YYYY-DD-MM, YYYY/DD/MM or YYYY.DD.MM, etc.\n\
    \    For other formats, choose the '--dateformat' accordingly."
  Collection_Month: "For incomplete collection dates, use this field instead of \"\
    Collection_Date\".\nMonth of year:\n    \"1\" = Jan,\n\t\"2\" = Feb,\n    ...\n\
    \    \"12\" = Dec"
  Collection_Year: "For incomplete collection dates, use this field instead of \"\
    Collection_Date\".\nFour digit year as string:\n\te.g. \"2023\" "
  Health_Status: "For human hosts:\n    Deceased\n    Recovered\n    In-patient\n\
    \    Out-patient\n    Long-term resident\n\nFor animal hosts:\n    Healthy\n \
    \   Sick\n    Dead\n    "
  Host: "Host or source name.,\n\tE.g. 'human', 'avian', 'chicken', 'Anas Acuta',\
    \ 'environment', etc."
  Host_Additional_info: Any other information about the host or source.
  Host_Age: 'Age as string, e.g. "15" '
  Host_Age_Unit: "Unit for the age:\n    \"Y\" for years\n    \"M\" for months\n \
    \   \"D\" for days."
  Host_Gender: 'Alternatives are ''M'' or ''F'' '
  Isolate_Id: Must be empty
  Isolate_Name**: "Mandatory.\n\tE.g. 'A/Brisbane/1444A/2010'"
  Lineage: '"pdm09", "Victoria", "Yamagata" '
  Location**: "Mandatory.,\n\tE.g., 'United Kingdom', 'Japan', 'China', 'United States',\
    \ etc."
  Location_Additional_info: e.g. the city name
  Note: 'A place for any extra notes about the sample. '
  Originating_Lab_Id: The numeric ID of the sample's originating laboratory, e.g.
    "2698". To find this number, run `epiflu_cli labs` (requires authentication).
  Originating_Sample_Id: Internal ID given to the sample by the originating lab.
  Oseltamivir_Resistance_geno: '"Unknown", "Resistant", "Sensitive", "Inconclusive" '
  Oseltamivir_Resistance_pheno: '"Unknown", "Resistant", "Sensitive", "Inconclusive" '
  Other_Resistance_geno: '"Unknown", "Resistant", "Sensitive", "Inconclusive" '
  Other_Resistance_pheno: '"Unknown", "Resistant", "Sensitive", "Inconclusive" '
  PMID: "List of PubMed ID's for referencing PubMed records related to the sample.\n\
    \tExample 1: 1234567\n\tExample 2: 1234567, 1234568"
  Passage_History: 'E.g. ''Original'', ''E2'',''MX/C1'', ... '
  Peramivir_Resistance_geno: '"Unknown", "Resistant", "Sensitive", "Inconclusive" '
  Peramivir_Resistance_pheno: '"Unknown", "Resistant", "Sensitive", "Inconclusive" '
  Segment_Ids: Must be empty String
  Seq_Id (HA): Name for the Segment (e.g. "A/test/Germany/testVIR8728/2023_HA")
  Seq_Id (HE): Name for the Segment (e.g. "A/test/Germany/testVIR8728/2023_HE")
  Seq_Id (MP): Name for the Segment (e.g. "A/test/Germany/testVIR8728/2023_MP")
  Seq_Id (NA): Name for the Segment (e.g. "A/test/Germany/testVIR8728/2023_NA")
  Seq_Id (NP): Name for the Segment (e.g. "A/test/Germany/testVIR8728/2023_NP")
  Seq_Id (NS): Name for the Segment (e.g. "A/test/Germany/testVIR8728/2023_NS")
  Seq_Id (P3): Name for the Segment (e.g. "A/test/Germany/testVIR8728/2023_P3")
  Seq_Id (PA): Name for the Segment (e.g. "A/test/Germany/testVIR8728/2023_PA")
  Seq_Id (PB1): Name for the Segment (e.g. "A/test/Germany/testVIR8728/2023_PB1")
  Seq_Id (PB2): Name for the Segment (e.g. "A/test/Germany/testVIR8728/2023_PB2")
  Submitting_Sample_Id: 'Internal ID given to the sample by the submitting lab '
  Subtype: 'e.g. "H5N1" '
  Zanamivir_Resistance_geno: '"Unknown", "Resistant", "Sensitive", "Inconclusive" '
  Zanamivir_Resistance_pheno: '"Unknown", "Resistant", "Sensitive", "Inconclusive" '
  province: Province of the sample location.
  sub_province: Sub-Province of the submission location
