from pandera import DataFrameSchema, Column, Check, Index, MultiIndex

schema = DataFrameSchema(
	columns={
		"Submission_Name": Column(
			dtype="object",
			checks=[
				Check.str_matches(r"^(?!\s*$).+"),
			],
			nullable=False,
			unique=True,
			coerce=False,
			description="Sequence identifier used in fasta file. This is used to create the fasta file for Genbank or GISAID.",
			title="submission name",
		),
		"Organism": Column(
			dtype="object",
			checks=[
				Check.str_matches(r"^(?!\s*$).+")
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="The most descriptive organism name for the samples.",
			title="organism",
		),
		"Database": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Citing authors. List of <b>Last, First Middle, suffix</b> separated by a semicolon \";\" E.g.: \"Baker, Howard Henry, Jr.; Powell, Earl Alexander, III.;\"",
			title="database",
		),
		"Submission_Position": Column(
			dtype="datetime64[ns]",
			checks=[
				Check.str_matches(r"[1-2][9|0]\d{2}-[0-1]\d-[0-3]\d|[1-2][9|0]\d{2}-[0-1]\d|[1-2][9|0]\d{2}")
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Collection date for sequence. Must be in a valid format based on ISO 8601: \"YYYY-MM-DD\", \"YYYY-MM\", or \"YYYY\". Time is not supported.",
			title="collection date",
		),
		"Submission_Type": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="NCBI BioProject ID.",
			title="bioproject",
		),
		"Submission_Date": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="NCBI BioProject ID.",
			title="bioproject",
		),
		"Submission_Status": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="NCBI BioProject ID.",
			title="bioproject",
		),
		"Submission_Directory": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="NCBI BioProject ID.",
			title="bioproject",
		),
		"Config_File": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="NCBI BioProject ID.",
			title="bioproject",
		),
		"Table2asn": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="NCBI BioProject ID.",
			title="bioproject",
		),
		"GFF_File": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="NCBI BioProject ID.",
			title="bioproject",
		),
		"Update_Date": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="NCBI BioProject ID.",
			title="bioproject",
		),
	},
     checks=None,
     index=None,
     dtype=None,
     coerce=False,
     strict=True,
     name="seqsender_log_schema",
     ordered=False,
     unique=None,
     report_duplicates="all",
     unique_column_names=True,
     add_missing_columns=False,
     title="seqsender log schema",
     description="Schema validation for seqsender submission log.",
)
