from pandera import DataFrameSchema, Column, Check, Index, MultiIndex

schema = DataFrameSchema(
	columns={
		"bs-sample_name": Column(
			dtype="object",
			checks=[
				Check.str_matches(r"^(?!\s*$).+"),
			],
			nullable=False,
			unique=True,
			coerce=False,
			required=True,
			description="Identifier name used for BioSample. Max length is 50 characters.",
			title="sample_name",
		),
		"bs-sample_title": Column(
			dtype="object",
			checks=[
				Check.str_matches(r"^(?!\s*$).+"),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Descriptive title for sample.",
			title="sample title",
		),
		"bs-sample_description": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Optional description for sample.",
			title="sample description",
		),
		"bs-isolate": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="identification or description of the specific individual from which this sample was obtained",
			title="isolate",
		),
		"bs-abs_air_humidity": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="actual mass of water vapor - mh20 - present in the air water vapor mixture",
			title="absolute air humidity",
		),
		"bs-air_temp": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="temperature of the air at the time of sampling",
			title="air temperature",
		),
		"bs-build_occup_type": Column(
			dtype="object",
			checks=Check.str_matches(r"(?i)(\W|^)(office|market|restaurant|residence|school|residential|commercial|low rise|high rise|wood framed|health care|airport|sports complex|missing|not applicable|not collected|not provided|restricted access)(\W|$)"),
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="primary function for which a building or discrete part of a building is intended to be used",
			title="building occupancy type",
		),
		"bs-building_setting": Column(
			dtype="object",
			checks=Check.str_matches(r"(?i)(\W|^)(urban|suburban|exurban|rural|missing|not applicable|not collected|not provided|restricted access)(\W|$)"),
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="location (geography) where a building is set",
			title="building setting",
		),
		"bs-carb_dioxide": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="carbon dioxide (gas) amount or concentration at the time of sampling",
			title="carbon dioxide",
		),
		"bs-env_broad_scale": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Add terms that identify the major environment type(s) where your sample was collected. Recommend subclasses of biome [ENVO:00000428]. Multiple terms can be separated by one or more pipes e.g.:  mangrove biome [ENVO:01000181]|estuarine biome [ENVO:01000020]",
			title="broad-scale environmental context",
		),
		"bs-env_local_scale": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Add terms that identify environmental entities having causal influences upon the entity at time of sampling, multiple terms can be separated by pipes, e.g.:  shoreline [ENVO:00000486]|intertidal zone [ENVO:00000316]",
			title="local-scale environmental context",
		),
		"bs-env_medium": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Add terms that identify the material displaced by the entity at time of sampling. Recommend subclasses of environmental material [ENVO:00010483]. Multiple terms can be separated by pipes e.g.: estuarine water [ENVO:01000301]|estuarine mud [ENVO:00002160]",
			title="environmental medium",
		),
		"bs-filter_type": Column(
			dtype="object",
			checks=Check.str_matches(r"(?i)(\W|^)(particulate air filter|chemical air filter|low-MERV pleated media|HEPA|electrostatic|gas-phase or ultraviolet air treatments|missing|not applicable|not collected|not provided|restricted access)(\W|$)"),
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="device which removes solid particulates or airborne molecular contaminants",
			title="filter type",
		),
		"bs-geo_loc_name": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Geographical origin of the sample; use the appropriate name from this list http://www.insdc.org/documents/country-qualifier-vocabulary. Use a colon to separate the country or ocean from more detailed information about the location, eg \"Canada: Vancouver\" or \"Germany: halfway down Zugspitze, Alps\"",
			title="geographic location",
		),
		"bs-heat_cool_type": Column(
			dtype="object",
			checks=Check.str_matches(r"(?i)(\W|^)(radiant system|heat pump|forced air system|steam forced heat|wood stove|missing|not applicable|not collected|not provided|restricted access)(\W|$)"),
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="methods of conditioning or heating a room or building",
			title="heating and cooling system type",
		),
		"bs-indoor_space": Column(
			dtype="object",
			checks=Check.str_matches(r"(?i)(\W|^)(bedroom|office|bathroom|foyer|kitchen|locker room|hallway|elevator|missing|not applicable|not collected|not provided|restricted access)(\W|$)"),
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="a distinguishable space within a structure, the purpose for which discrete areas of a building is used",
			title="indoor space",
		),
		"bs-isolation_source": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Describes the physical, environmental and/or local geographical source of the biological sample from which the sample was derived.",
			title="isolation source",
		),
		"bs-lat_lon": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="The geographical coordinates of the location where the sample was collected. Specify as degrees latitude and longitude in format \"d[d.dddd] N|S d[dd.dddd] W|E\", eg, 38.98 N 77.11 W",
			title="latitude and longitude",
		),
		"bs-light_type": Column(
			dtype="object",
			checks=Check.str_matches(r"(?i)(\W|^)(natural light|electric light|no light|missing|not applicable|not collected|not provided|restricted access)(\W|$)"),
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="application of light to achieve some practical or aesthetic effect. Lighting includes the use of both artificial light sources such as lamps and light fixtures, as well as natural illumination by capturing daylight. Can also include absence of light",
			title="light type",
		),
		"bs-occup_samp": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="number of occupants present at time of sample within the given space",
			title="occupancy at sampling",
		),
		"bs-occupant_dens_samp": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="average number of occupants at time of sampling per square footage",
			title="occupant density at sampling",
		),
		"bs-organism_count": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="total count of any organism per gram or volume of sample,should include name of organism followed by count; can include multiple organism counts",
			title="organism count",
		),
		"bs-rel_air_humidity": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="partial vapor and air pressure, density of the vapor and air, or by the actual mass of the vapor and air",
			title="relative air humidity",
		),
		"bs-space_typ_state": Column(
			dtype="object",
			checks=Check.str_matches(r"(?i)(\W|^)(typical occupied|typically unoccupied|missing|not applicable|not collected|not provided|restricted access)(\W|$)"),
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="customary or normal state of the space",
			title="space typical state",
		),
		"bs-typ_occupant_dens": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="customary or normal density of occupants",
			title="typical occupant density",
		),
		"bs-ventilation_type": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="ventilation system used in the sampled premises",
			title="ventilation type",
		),
		"bs-address": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The street name and building number where the sampling occurred",
			title="address",
		),
		"bs-adj_room": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="List of rooms (room number, room name) immediately adjacent to the sampling room",
			title="adjacent rooms",
		),
		"bs-aero_struc": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Aerospace structures typically consist of thin plates with stiffeners for the external surfaces, bulkheads and frames to support the shape and fasteners such as welds, rivets, screws and bolts to hold the components together, e.g., plane, glider",
			title="aerospace structure",
		),
		"bs-amount_light": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The unit of illuminance and luminous emittance, measuring luminous flux per unit area",
			title="amount of light",
		),
		"bs-arch_struc": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="An architectural structure is a human-made, free-standing, immobile outdoor construction, e.g., building, shed, home",
			title="architectural structure",
		),
		"bs-avg_dew_point": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The average of dew point measures taken at the beginning of every hour over a 24 hour period on the sampling day",
			title="average dew point",
		),
		"bs-avg_occup": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Daily average occupancy of room. Indicate the number of person(s) daily occupying the sampling room",
			title="average daily occupancy",
		),
		"bs-avg_temp": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The average of temperatures taken at the beginning of every hour over a 24 hour period on the sampling day",
			title="average temperature",
		),
		"bs-bathroom_count": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The number of bathrooms in the building",
			title="bathroom count",
		),
		"bs-bedroom_count": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The number of bedrooms in the building",
			title="bedroom count",
		),
		"bs-build_docs": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The building design, construction and operation documents, e.g., building information model, commissioning report, complaint logs, contract administration, cost estimate, janitorial schedules or logs, maintenance plans, schedule, sections, shop drawings, submittals, ventilation system, windows",
			title="design, construction, and operation documents",
		),
		"bs-built_struc_age": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The age of the built structure since construction",
			title="built structure age",
		),
		"bs-built_struc_set": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The characterization of the location of the built structure as high or low human density, e.g., urban, rural",
			title="built structure setting",
		),
		"bs-built_struc_type": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="A physical structure that is a body or assemblage of bodies in space to form a system capable of supporting loads",
			title="built structure type",
		),
		"bs-ceil_area": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The area of the ceiling space within the room",
			title="ceiling area",
		),
		"bs-ceil_cond": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The physical condition of the ceiling at the time of sampling, e.g., new, visible wear, needs repair, damaged, rupture",
			title="ceiling condition",
		),
		"bs-ceil_finish_mat": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The type of material used to finish a ceiling, e.g., drywall, mineral fibre, tiles, PVC, plasterboard, metal, fiberglass, stucco, mineral wool/calcium silicate, wood",
			title="ceiling finish material",
		),
		"bs-ceil_struc": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The construction format of the ceiling, e.g., wood frame, concrete",
			title="ceiling structure",
		),
		"bs-ceil_texture": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The feel, appearance, or consistency of a ceiling surface, e.g., crows feet, crows-foot stomp, double skip, hawk and trowel, knockdown, popcorn, orange peel, rosebud stomp, Santa-Fe texture, skip trowel, smooth, stomp knockdown, swirl",
			title="ceiling texture",
		),
		"bs-ceil_thermal_mass": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The ability of the ceiling to provide inertia against temperature fluctuations. Generally this means concrete that is exposed. A metal deck that supports a concrete slab will act thermally as long as it is exposed to room air flow",
			title="ceiling thermal mass",
		),
		"bs-ceil_type": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The type of ceiling according to the ceiling's appearance or construction, e.g., cathedral, dropped, concave, barrel-shaped, coffered, cove, stretched",
			title="ceiling type",
		),
		"bs-ceil_water_mold": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Signs of the presence of mold or mildew on the ceiling, e.g., presence of mold visible, no presence of mold visible",
			title="ceiling signs of water/mold",
		),
		"bs-collection_method": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Process used to collect the sample, e.g., bronchoalveolar lavage (BAL)",
			title="collection method",
		),
		"bs-cool_syst_id": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The cooling system identifier",
			title="cooling system identifier",
		),
		"bs-date_last_rain": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The date of the last time it rained",
			title="date last rain",
		),
		"bs-derived_from": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Indicates when one BioSample was derived from another BioSample. Value should include BioSample accession number(s) (SAMNxxxxxxxx).",
			title="derived from",
		),
		"bs-dew_point": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="temperature to which a given parcel of humid air must be cooled, at constant barometric pressure, for water vapor to condense into water.",
			title="dew point",
		),
		"bs-door_comp_type": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The composite type of the door, e.g., metal covered, revolving, sliding, telescopic",
			title="door type, composite",
		),
		"bs-door_cond": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The physical condition of the door, e.g., damaged, needs repair, new, rupture, visible wear",
			title="door condition",
		),
		"bs-door_direct": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The direction the door opens, e.g., inward, outward, sideways",
			title="door direction of opening",
		),
		"bs-door_loc": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The relative location of the door in the room, e.g., north, south, east, west",
			title="door location",
		),
		"bs-door_mat": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The material the door is composed of, e.g., aluminum, cellular PVC, engineered plastic, fiberboard, fiberglass, metal, thermoplastic alloy, vinyl, wood, wood/plastic composite",
			title="door material",
		),
		"bs-door_move": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The type of movement of the door, e.g., collapsible, folding, revolving, rolling shutter, sliding, swinging",
			title="door movement",
		),
		"bs-door_size": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The size of the door",
			title="door area or size",
		),
		"bs-door_type": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The type of door material, e.g., composite, metal, wooden",
			title="door type",
		),
		"bs-door_type_metal": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The type of metal door, e.g., collapsible, corrugated steel, hollow, rolling shutters, steel plate",
			title="door type, metal",
		),
		"bs-door_type_wood": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The type of wood door, e.g., bettened and ledged, battened, ledged and braced, battened, ledged and framed, battened, ledged, braced and frame, framed and paneled, glashed or sash, flush, louvered, wire gauged",
			title="door type, wood",
		),
		"bs-door_water_mold": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Signs of the presence of mold or mildew on a door, e.g., presence of mold visible, no presence of mold visible",
			title="door signs of water/mold",
		),
		"bs-drawings": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The buildings architectural drawings, e.g., operation, as built, construction, bid, design, building navigation map, diagram, sketch",
			title="drawings",
		),
		"bs-elevator": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The number of elevators within the built structure",
			title="elevator count",
		),
		"bs-escalator": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The number of escalators within the built structure",
			title="escalator count",
		),
		"bs-exp_duct": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The amount of exposed ductwork in the room",
			title="exposed ductwork",
		),
		"bs-exp_pipe": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The number of exposed pipes in the room",
			title="exposed pipes",
		),
		"bs-experimental_factor": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Variable aspect of experimental design",
			title="experimental factor",
		),
		"bs-ext_door": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The number of exterior doors in the built structure",
			title="exterior door count",
		),
		"bs-ext_wall_orient": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The orientation of the exterior wall, e.g., north, south, east, west, northeast, southeast, southwest, northwest",
			title="orientations of exterior wall",
		),
		"bs-ext_window_orient": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The compass direction the exterior window of the room is facing, e.g., north, south, east, west, northeast, southeast, southwest, northwest",
			title="orientations of exterior window",
		),
		"bs-fireplace_type": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="A firebox with chimney, e.g., gas burning, wood burning",
			title="fireplace type",
		),
		"bs-floor_age": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The time period since installment of the carpet or flooring",
			title="floor age",
		),
		"bs-floor_area": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The area of the floor space within the room",
			title="floor area",
		),
		"bs-floor_cond": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The physical condition of the floor at the time of sampling, e.g., new, visible wear, needs repair, damaged, rupture",
			title="floor condition",
		),
		"bs-floor_count": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The number of floors in the building, including basements and mechanical penthouse",
			title="floor count",
		),
		"bs-floor_finish_mat": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The floor covering type; the finished surface that is walked on, e.g., tile, wood strip or parquet, carpet, rug, laminate wood, lineoleum, vinyl composition tile, sheet vinyl, stone, bamboo, cork, terrazo, concrete, none;specify unfinished, sealed, clear finish, paint",
			title="floor finish material",
		),
		"bs-floor_struc": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Refers to the structural elements and subfloor upon which the finish flooring is installed, e.g., balcony, floating floor, glass floor, raised floor, sprung floor, wood-framed, concrete",
			title="floor structure",
		),
		"bs-floor_thermal_mass": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The ability of the floor to provide inertia against temperature fluctuations",
			title="floor thermal mass",
		),
		"bs-floor_water_mold": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Signs of the presence of mold or mildew in a room, e.g., mold odor, wet floor, water stains, wall discoloration, floor discoloration, ceiling discoloration, peeling paint or wallpaper, bulging walls, condensation",
			title="floor signs of water/mold",
		),
		"bs-freq_clean": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The number of times the sample location is cleaned, e.g., daily, weekly, monthly, quarterly, annually",
			title="frequency of cleaning",
		),
		"bs-freq_cook": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The number of times a meal is cooked per week",
			title="frequency of cooking",
		),
		"bs-furniture": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The types of furniture present in the sampled room, e.g., cabinet, chair, desks",
			title="furniture",
		),
		"bs-hall_count": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The total count of hallways and cooridors in the built structure",
			title="hallway/corridor count",
		),
		"bs-handidness": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The handidness of the individual sampled, e.g., ambidexterity, left handedness, mixed-handedness, right handedness",
			title="handidness",
		),
		"bs-heat_deliv_loc": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The location of heat delivery within the room, e.g., north, south, east, west",
			title="heating delivery locations",
		),
		"bs-heat_sys_deliv_meth": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The method by which the heat is delivered through the system, e.g., conductive, radiant",
			title="heating system delivery method",
		),
		"bs-heat_system_id": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The heating system identifier",
			title="heating system identifier",
		),
		"bs-height_carper_fiber": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The average carpet fiber height in the indoor environment",
			title="height carpet fiber mat",
		),
		"bs-indoor_surf": Column(
			dtype="object",
			checks=Check.str_matches(r"(?i)(\W|^)(counter top|window|wall|cabinet|ceiling|door|shelving|vent cover|missing|not applicable|not collected|not provided|restricted access)(\W|$)"),
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="type of indoor surface",
			title="indoor surface",
		),
		"bs-inside_lux": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The recorded value at sampling time (power density)",
			title="inside lux light",
		),
		"bs-int_wall_cond": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The physical condition of the wall at the time of sampling, e.g., new, visible wear, needs repair, damaged, rupture",
			title="interior wall condition",
		),
		"bs-last_clean": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The last time the floor was cleaned (swept, mopped, vacuumed)",
			title="last time swept/mopped/vacuumed",
		),
		"bs-max_occup": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The maximum amount of people allowed in the indoor environment",
			title="maximum occupancy",
		),
		"bs-mech_struc": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Mechanical structure: a moving structure, e.g., subway, coach, carriage, elevator, escalator, boat, train, car, bus",
			title="mechanical structure",
		),
		"bs-metagenome_source": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="describes the original source of a metagenome assembled genome (MAG). Examples: soil metagenome, gut metagenome",
			title="metagenome source",
		),
		"bs-neg_cont_type": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The substance or equipment used as a negative control in an investigation, e.g., distilled water, phosphate buffer, empty collection device, empty collection tube, DNA-free PCR mix, sterile swab, sterile syringe",
			title="negative control type",
		),
		"bs-number_pets": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The number of pets residing in the sampled space",
			title="number of pets",
		),
		"bs-number_plants": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The number of plant(s) in the sampling space",
			title="number of houseplants",
		),
		"bs-number_resident": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The number of individuals currently occupying in the sampling location",
			title="number of residents",
		),
		"bs-occup_document": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The type of documentation of occupancy, e.g., automated count, estimate, manual count, videos",
			title="occupancy documentation",
		),
		"bs-omics_observ_id": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="A unique identifier of the omics-enabled observatory (or comparable time series) your data derives from. This identifier should be provided by the OMICON ontology; if you require a new identifier for your time series, contact the ontology's developers. Information is available here: https://github.com/GLOMICON/omicon. This field is only applicable to records which derive from an omics time-series or observatory.",
			title="Omics Observatory ID",
		),
		"bs-pos_cont_type": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The substance, mixture, product, or apparatus used to verify that a process which is part of an investigation delivers a true positive",
			title="positive control type",
		),
		"bs-pres_animal_insect": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The type and number of animals or insects present in the sampling space, e.g., cat 10, dog 2, rodent 100, snake 1",
			title="presence of pets, animals, or insects",
		),
		"bs-quad_pos": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The quadrant position of the sampling room within the building, e.g., north side, west side, south side, east side",
			title="quadrant position",
		),
		"bs-ref_biomaterial": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Primary publication or genome report",
			title="reference for biomaterial",
		),
		"bs-rel_humidity_out": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The recorded outside relative humidity value at the time of sampling",
			title="outside relative humidity",
		),
		"bs-rel_samp_loc": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The sampling location within the train car, e.g., edge of car, center of car, under a seat",
			title="relative sampling location",
		),
		"bs-rel_to_oxygen": Column(
			dtype="object",
			checks=Check.str_matches(r"(?i)(\W|^)(aerobe|anaerobe|facultative|microaerophilic|microanaerobe|obligate aerobe|obligate anaerobe|missing|not applicable|not collected|not provided|restricted access)(\W|$)"),
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Is this organism an aerobe, anaerobe? Please note that aerobic and anaerobic are valid descriptors for microbial environments, eg, aerobe, anaerobe, facultative, microaerophilic, microanaerobe, obligate aerobe, obligate anaerobe, missing, not applicable, not collected, not provided, restricted access",
			title="relationship to oxygen",
		),
		"bs-room_air_exch_rate": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The rate at which outside air replaces indoor air in a given space",
			title="room air exchange rate",
		),
		"bs-room_architec_elem": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The unique details and component parts that, together, form the architecture of a distinguisahable space within a built structure",
			title="room architectural elements",
		),
		"bs-room_condt": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The condition of the room at the time of sampling, e.g., new, visible wear, needs repair, damaged, rupture, visible signs of mold/mildew",
			title="room condition",
		),
		"bs-room_connected": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="List of rooms connected to the sampling room by a doorway, e.g., attic, bathroom, closet, conference room, elevator, examining room, hallway, kitchen, mail room, office, stairwell",
			title="rooms connected by a doorway",
		),
		"bs-room_count": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The total count of rooms in the built structure including all room types",
			title="room count",
		),
		"bs-room_dim": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The length, width and height of sampling room",
			title="room dimensions",
		),
		"bs-room_door_dist": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Distance between doors (meters) in the hallway between the sampling room and adjacent rooms",
			title="room door distance",
		),
		"bs-room_door_share": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="List of room(s) (room number, room name) sharing a door with the sampling room",
			title="rooms that share a door with sampling room",
		),
		"bs-room_hallway": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="List of room(s) (room number, room name) located in the same hallway as sampling room",
			title="rooms that are on the same hallway",
		),
		"bs-room_loc": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The position of the room within the building, e.g., corner room, interior room, exterior wall",
			title="room location in building",
		),
		"bs-room_moist_dam_hist": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The history of moisture damage or mold in the past 12 months. Number of events of moisture damage or mold observed",
			title="room moisture damage or mold history",
		),
		"bs-room_net_area": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The net floor area of sampling room. Net area excludes wall thicknesses",
			title="room net area",
		),
		"bs-room_occup": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Count of room occupancy at time of sampling",
			title="room occupancy",
		),
		"bs-room_samp_pos": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The horizontal sampling position in the room relative to architectural elements, e.g., north corner, south corner, west corner, east corner, northeast corner, northwest corner, southeast corner, southwest corner, center",
			title="room sampling position",
		),
		"bs-room_type": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The main purpose or activity of the sampling room. A room is any distinguishable space within a structure, e.g., attic, bathroom, closet, conference room, elevator, examining room, hallway, kitchen, mail room, private office, open office, stairwell,restroom, lobby, vestibule, mechanical or electrical room, data center, laboratory_wet, laboratory_dry, gymnasium, natatorium, auditorium, lockers, cafe, warehouse",
			title="room type",
		),
		"bs-room_vol": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Volume of sampling room",
			title="room volume",
		),
		"bs-room_wall_share": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="List of room(s) (room number, room name) sharing a wall with the sampling room",
			title="rooms that share a wall with sampling room",
		),
		"bs-room_window_count": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Number of windows in the room",
			title="room window count",
		),
		"bs-samp_collect_device": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Method or device employed for collecting sample",
			title="sample collection device or method",
		),
		"bs-samp_floor": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The floor of the building, where the sampling room is located, e.g., 1st floor, 2nd floor, basement, lobby",
			title="sampling floor",
		),
		"bs-samp_mat_process": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Processing applied to the sample during or after isolation",
			title="sample material processing",
		),
		"bs-samp_room_id": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Sampling room number. This ID should be consistent with the designations on the building floor plans",
			title="sampling room ID or name",
		),
		"bs-samp_size": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Amount or size of sample (volume, mass or area) that was collected",
			title="sample size",
		),
		"bs-samp_sort_meth": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="method by which samples are sorted",
			title="sample size sorting method",
		),
		"bs-samp_time_out": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The recent and long term history of outside sampling",
			title="sampling time outside",
		),
		"bs-samp_vol_we_dna_ext": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="volume (mL) or weight (g) of sample processed for DNA extraction",
			title="sample volume or weight for DNA extraction",
		),
		"bs-samp_weather": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The weather on the sampling day, e.g., clear sky, cloudy, foggy, hail, rain, snow, sleet, sunny, windy",
			title="sampling day weather",
		),
		"bs-season": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The season when sampling occurred. Any of the four periods into which the year is divided by the equinoxes and solstices. This field accepts terms listed under season (http://purl.obolibrary.org/obo/NCIT_C94729)",
			title="season",
		),
		"bs-season_use": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The seasons the space is occupied, e.g., spring, summer, fall, winter",
			title="seasonal use",
		),
		"bs-shad_dev_water_mold": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Signs of the presence of mold or mildew on the shading device, e.g., presence of mold visible, no presence of mold visible",
			title="shading device signs of water/mold",
		),
		"bs-shading_device_cond": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The physical condition of the shading device at the time of sampling, e.g., damaged, needs repair, new, rupture, visible wear",
			title="shading device condition",
		),
		"bs-shading_device_loc": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The location of the shading device in relation to the built structure, e.g., exterior, interior",
			title="shading device location",
		),
		"bs-shading_device_mat": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The material the shading device is composed of",
			title="shading device material",
		),
		"bs-shading_device_type": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The type of shading device, e.g., bahama shutters, exterior roll blind, gambrel awning, hood awning, porchroller awning, sarasota shutters, slatted aluminum, solid aluminum awning, sun screen, tree, trellis, venetian awning",
			title="shading device type",
		),
		"bs-size_frac": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Filtering pore size used in sample preparation, e.g., 0-0.22 micrometer",
			title="size fraction selected",
		),
		"bs-source_material_id": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="unique identifier assigned to a material sample used for extracting nucleic acids, and subsequent sequencing. The identifier can refer either to the original material collected or to any derived sub-samples.",
			title="source material identifiers",
		),
		"bs-specific": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The building specifications, e.g., operation, as built, construction, bid, design, photos",
			title="specifications",
		),
		"bs-specific_humidity": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The mass of water vapour in a unit mass of moist air, usually expressed as grams of vapour per kilogram of air, or, in air conditioning, as grains per pound",
			title="specific humidity",
		),
		"bs-substructure_type": Column(
			dtype="object",
			checks=Check.str_matches(r"(?i)(\W|^)(crawlspace|slab on grade|basement)(\W|$)"),
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="substructure or under building is that largely hidden section of the building which is built off the foundations to the ground floor level",
			title="substructure type",
		),
		"bs-surf_air_cont": Column(
			dtype="object",
			checks=Check.str_matches(r"(?i)(\W|^)(dust|organic matter|particulate matter|volatile organic compounds|biological contaminants|radon|nutrients|biocides)(\W|$)"),
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="contaminant identified on surface",
			title="surface-air contaminant",
		),
		"bs-surf_humidity": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="surfaces: water activity as a function of air and material moisture",
			title="surface humidity",
		),
		"bs-surf_material": Column(
			dtype="object",
			checks=Check.str_matches(r"(?i)(\W|^)(concrete|wood|stone|tile|plastic|glass|vinyl|metal|carpet|stainless steel|paint|cinder blocks|hay bales|stucco|adobe|missing|not applicable|not collected|not provided|restricted access)(\W|$)"),
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="surface materials at the point of sampling",
			title="surface material",
		),
		"bs-surf_moisture": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="water held on a surface",
			title="surface moisture",
		),
		"bs-surf_moisture_ph": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="pH measurement of surface",
			title="surface moisture pH",
		),
		"bs-surf_temp": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="temperature of the surface at the time of sampling",
			title="surface temperature",
		),
		"bs-temp_out": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The recorded temperature value at sampling time outside",
			title="temperature outside house",
		),
		"bs-train_line": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The subway line name, e.g., red, green, orange",
			title="train line",
		),
		"bs-train_stat_loc": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The train station collection location, e.g., south station above ground, south station underground, south station amtrak, forest hills, riverside",
			title="train station collection location",
		),
		"bs-train_stop_loc": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The train stop collection location, e.g., end, mid, downtown",
			title="train stop collection location",
		),
		"bs-vis_media": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The building visual media, e.g., photos, videos, commonly of the building, site context (adjacent buildings, vegetation, terrain, streets), interiors, equipment, 3D scans",
			title="visual media",
		),
		"bs-wall_area": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The total area of the sampled room's walls",
			title="wall area",
		),
		"bs-wall_const_type": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The building class of the wall defined by the composition of the building elements and fire-resistance rating, e.g., frame construction, joisted masonry, light noncombustible, masonry noncombustible, modified fire resistive, fire resistive",
			title="wall construction type",
		),
		"bs-wall_finish_mat": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The material utilized to finish the outer most layer of the wall, e.g., plaster, gypsum plaster, veneer plaster, gypsum board, tile, terrazzo, stone facing, acoustical treatment, wood, metal, masonry",
			title="wall finish material",
		),
		"bs-wall_height": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The average height of the walls in the sampled room",
			title="wall height",
		),
		"bs-wall_loc": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The relative location of the wall within the room, e.g., north, south, east, west",
			title="wall location",
		),
		"bs-wall_surf_treatment": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The surface treatment of interior wall, e.g., painted, wall paper, no treatment, paneling, stucco, fabric",
			title="wall surface treatment",
		),
		"bs-wall_texture": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The feel, appearance, or consistency of a wall surface, e.g., crows feet, crows-foot stomp, double skip, hawk and trowel, knockdown, popcorn, orange peel, rosebud stomp, Santa-Fe texture, skip trowel, smooth, stomp knockdown, swirl",
			title="wall texture",
		),
		"bs-wall_thermal_mass": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The ability of the wall to provide inertia against temperature fluctuations. Generally this means concrete or concrete block that is either exposed or covered only with paint",
			title="wall thermal mass",
		),
		"bs-wall_water_mold": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Signs of the presence of mold or mildew on a wall, e.g., presence of mold visible, no presence of mold visible",
			title="wall signs of water/mold",
		),
		"bs-water_feat_size": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The size of the water feature",
			title="water feature size",
		),
		"bs-water_feat_type": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The type of water feature present within the building being sampled, e.g., fountain, pool, standing feature, stream, waterfall",
			title="water feature type",
		),
		"bs-weekday": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The day of the week when sampling occurred, e.g., monday, tuesday, wednesday, thursday, friday, saturday, sunday",
			title="weekday",
		),
		"bs-window_cond": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The physical condition of the window at the time of sampling, e.g., damaged, needs repair, new, rupture, visible wear",
			title="window condition",
		),
		"bs-window_cover": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The type of window covering, e.g., blinds, curtains, none",
			title="window covering",
		),
		"bs-window_horiz_pos": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The horizontal position of the window on the wall, e.g., left, middle, right",
			title="window horizontal position",
		),
		"bs-window_loc": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The relative location of the window within the room, e.g., north, south, east, west",
			title="window location",
		),
		"bs-window_mat": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The type of material used to finish a window, e.g., clad, fiberglass, metal, vinyl, wood",
			title="window material",
		),
		"bs-window_open_freq": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The number of times windows are opened per week",
			title="window open frequency",
		),
		"bs-window_size": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The window's length and width",
			title="window area/size",
		),
		"bs-window_status": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Defines whether the windows were open or closed during environmental testing, e.g., closed, open",
			title="window status",
		),
		"bs-window_type": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The type of windows, e.g., single-hung sash window, horizontal sash window, fixed window",
			title="window type",
		),
		"bs-window_vert_pos": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The vertical position of the window on the wall, e.g., bottom, middle, top, low, middle, high",
			title="window vertical position",
		),
		"bs-window_water_mold": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Signs of the presence of mold or mildew on the window, e.g., presence of mold visible, no presence of mold visible",
			title="window signs of water/mold",
		),
		"bs-title": Column(
			dtype="object",
			checks=[
				Check(lambda s: s.nunique() == 1),
			],
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Optional internal field for how the BioSample submission should be named when viewed from the NCBI submission portal. If not provided, when performing submissions <--submission_name> with the suffix \"-BS\" will be used instead.",
			title="biosample submission portal name",
		),
		"bs-comment": Column(
			dtype="object",
			checks=[
				Check(lambda s: s.nunique() == 1),
			],
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Optional internal field explaining the purpose of the submission for when interacting and resolving submission issues with NCBI.",
			title="biosample submission portal description",
		)
	},
	checks=None,
	index=None,
	coerce=False,
	strict="filter",
	name="biosample_package_MIMAG.built.6.0_schema",
	ordered=False,
	unique=None,
	report_duplicates="all",
	unique_column_names=True,
	add_missing_columns=False,
	title="BioSample package MIMAG.built.6.0 schema",
	description="Schema validation for BioSample database using MIMAG.built.6.0 package.",
)