from pandera import DataFrameSchema, Column, Check, Index, MultiIndex

schema = DataFrameSchema(
	columns={
		"bs-sample_name": Column(
			dtype="object",
			checks=[
				Check.str_matches(r"^(?!\s*$).+"),
			],
			nullable=False,
			unique=True,
			coerce=False,
			required=True,
			description="Identifier name used for BioSample. Max length is 50 characters.",
			title="sample_name",
		),
		"bs-sample_title": Column(
			dtype="object",
			checks=[
				Check.str_matches(r"^(?!\s*$).+"),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Descriptive title for sample.",
			title="sample title",
		),
		"bs-sample_description": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Optional description for sample.",
			title="sample description",
		),
		"bs-geo_loc_name": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Geographical origin of the sample; use the appropriate name from this list http://www.insdc.org/documents/country-qualifier-vocabulary. Use a colon to separate the country or ocean from more detailed information about the location, eg \"Canada: Vancouver\" or \"Germany: halfway down Zugspitze, Alps\"",
			title="geographic location",
		),
		"bs-isolation_source": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Describes the physical, environmental and/or local geographical source of the biological sample from which the sample was derived.",
			title="isolation source",
		),
		"bs-ww_population": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Number of persons contributing wastewater to this sample collection site; if unknown, estimate to the nearest order of magnitude, e.g., 10000.  If no estimate is available, input NA.",
			title="wastewater population",
		),
		"bs-ww_sample_duration": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Duration of composite sample collected, in units of hours, e.g., 24. Specify integer values. If the sample is not a composite sample, use 0.",
			title="wastewater sample duration",
		),
		"bs-ww_sample_matrix": Column(
			dtype="object",
			checks=Check.str_matches(r"(?i)(\W|^)(raw wastewater|sewer pipeline sediments|post grit removal|primary sludge|primary effluent|secondary sludge|secondary effluent|other|missing|not applicable|not collected|not provided|restricted access)(\W|$)"),
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="The wastewater matrix that was sampled",
			title="wastewater sample matrix",
		),
		"bs-ww_sample_type": Column(
			dtype="object",
			checks=Check.str_matches(r"(?i)(\W|^)(grab|composite|swab-grab|swab-composite|missing|not applicable|not collected|not provided|restricted access)(\W|$)"),
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Type of wastewater sample collected",
			title="wastewater sample type",
		),
		"bs-ww_surv_target_1": Column(
			dtype="object",
			checks=None,
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Taxonomic name of the surveillance target. For the COVID-19 response, use 'SARS-CoV-2'.",
			title="wastewater surveillance target 1",
		),
		"bs-ww_surv_target_1_known_present": Column(
			dtype="object",
			checks=Check.str_matches(r"(?i)(\W|^)(no|yes)(\W|$)"),
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Is genetic material of the surveillance target(s) known to the submitter to be present in this wastewater sample? Presence defined as microbiological evidence of the target organism in the wastewater sample, such as genetic- or culture-based detection.",
			title="wastewater surveillance target 1 known present",
		),
		"bs-collected_by": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Name of persons or institute who collected the sample",
			title="collected by",
		),
		"bs-purpose_of_ww_sampling": Column(
			dtype="object",
			checks=Check.str_matches(r"(?i)(\W|^)(public health surveillance community-level|public health surveillance institution-level|public health surveillance building-level|research|other|missing|not applicable|not collected|not provided|restricted access)(\W|$)"),
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The reason the sample was collected",
			title="purpose of wastewater sampling",
		),
		"bs-purpose_of_ww_sequencing": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The reason the sample was sequenced, e.g., identification of mutations within a specific region, presence of clinically known mutations, or diversity of mutations across entire genome",
			title="purpose of wastewater sequencing",
		),
		"bs-sequenced_by": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The name of the agency that generated the sequence, e.g., Centers for Disease Control and Prevention",
			title="sequenced by",
		),
		"bs-ww_endog_control_1": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The name of an organism, gene, or compound used as an endogenous wastewater control, e.g., pepper mild mottle virus",
			title="wastewater endogenous control 1",
		),
		"bs-ww_endog_control_1_conc": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The concentration of the endogenous control specified in 'ww_endog_control_1' on a per wastewater unit basis, e.g., 700000000",
			title="wastewater endogenous control 1 concentration",
		),
		"bs-ww_endog_control_1_protocol": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The protocol used to quantify 'ww_endog_control_1'. Specify a reference, website, or brief description.",
			title="wastewater endogenous control 1 protocol",
		),
		"bs-ww_endog_control_1_units": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The units of the value specified in 'ww_endog_control_1_conc', e.g., copies/L wastewater",
			title="wastewater endogenous control 1 units",
		),
		"bs-ww_endog_control_2": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The name of an organism, gene, or compound used as an endogenous wastewater control, e.g., crassphage",
			title="wastewater endogenous control 2",
		),
		"bs-ww_endog_control_2_conc": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The concentration of the endogenous control specified in 'ww_endog_control_2' on a per wastewater unit basis, e.g., 140000000",
			title="wastewater endogenous control 2 concentration",
		),
		"bs-ww_endog_control_2_protocol": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The protocol used to quantify 'ww_endog_control_2'. Specify a reference, website, or brief description.",
			title="wastewater endogenous control 2 protocol",
		),
		"bs-ww_endog_control_2_units": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The units of the value specified in 'ww_endog_control_2_conc', e.g., copies/L wastewater",
			title="wastewater endogenous control 2 units",
		),
		"bs-ww_flow": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Daily volumetric flow through collection site, in units of liters per day, e.g., 110000000.",
			title="wastewater flow",
		),
		"bs-ww_industrial_effluent_percent": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Percentage of industrial effluents received by wastewater treatment plant, e.g., 10",
			title="wastewater industrial effluent percent",
		),
		"bs-ww_ph": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="pH measurement of the sample, or liquid portion of sample, or aqueous phase of the fluid, e.g., 7.2",
			title="wastewater pH",
		),
		"bs-ww_population_source": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Source of value specified in 'ww_population', e.g., wastewater utility billing records, population of jurisdiction encompassing the wastewater service area, census blocks clipped to wastewater service area polygon",
			title="wastewater population source",
		),
		"bs-ww_pre_treatment": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Describe any process of pre-treatment that removes materials that can be easily collected from the raw wastewater, e.g., flow equilibration basin promotes settling of some solids",
			title="wastewater pre-treatment",
		),
		"bs-ww_primary_sludge_retention_time": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The time primary sludge remains in tank, in hours, e.g., 4.",
			title="wastewater primary sludge retention time",
		),
		"bs-ww_processing_protocol": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The protocol used to process the wastewater sample. Processing includes laboratory procedures prior to and including nucleic acid purification (e.g., pasteurization, concentration, extraction, etc). Specify a reference, website, or brief description.",
			title="wastewater processing protocol",
		),
		"bs-ww_sample_salinity": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Salinity is the total concentration of all dissolved salts in a liquid or solid (in the form of an extract obtained by centrifugation) sample or derived from the conductivity measurement (practical salinity) in milligrams per liter, e.g., 100.",
			title="wastewater sample salinity",
		),
		"bs-ww_sample_site": Column(
			dtype="object",
			checks=Check.str_matches(r"(?i)(\W|^)(correctional facility|long-term care facility|hospital|child day care|school|college or university|social services shelter|other residential building|ship|airplane|airport|septic tank|other holding tank|wastewater treatment plant|wastewater lagoon|sewer pipeline|food or meat processing plant|other|missing|not applicable|not collected|not provided|restricted access)(\W|$)"),
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The type of site where the wastewater sample was collected",
			title="wastewater sample site",
		),
		"bs-ww_surv_jurisdiction": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="A jurisdiction identifer that can be used to support linking the sample to a public health surveillance system, e.g., va",
			title="wastewater surveillance jurisdiction",
		),
		"bs-ww_surv_system_sample_id": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The sample ID used for submission to a public health surveillance system (e.g., CDC's National Wastewater Surveillance System), e.g., s123456",
			title="wastewater surveillance system sample ID",
		),
		"bs-ww_surv_target_1_conc": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The concentration of the wastewater surveillance target specified in 'ww_surv_target_1' on a per wastewater unit basis, e.g., 200000",
			title="wastewater surveillance target 1 concentration",
		),
		"bs-ww_surv_target_1_conc_unit": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The units of the value specified in 'ww_surv_target_1_conc', e.g., copies/L wastewater",
			title="wastewater surveillance target 1 conc unit",
		),
		"bs-ww_surv_target_1_extract": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Measured amount of surveillance target in the nucleic acid extract that was sequenced; on a per extract unit basis, rather than on a per wastewater sample unit basis, e.g., 100000",
			title="wastewater surveillance target 1 extract",
		),
		"bs-ww_surv_target_1_extract_unit": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The units of the value specified in 'ww_surv_target_1_extract', e.g., copies/microliter extract",
			title="wastewater surveillance target 1 extract unit",
		),
		"bs-ww_surv_target_1_gene": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The name of the gene quantified for the the surveillance target specified in 'ww_surv_target_1', e.g., N gene",
			title="wastewater surveillance target 1 gene",
		),
		"bs-ww_surv_target_1_protocol": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The protocol used to quantify 'ww_surv_target_1'. Specify a reference, website, or brief description.",
			title="wastewater surveillance target 1 protocol",
		),
		"bs-ww_surv_target_2": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Taxonomic name of the surveillance target, eg, Norovirus",
			title="wastewater surveillance target 2",
		),
		"bs-ww_surv_target_2_conc": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The concentration of the wastewater surveillance target specified in 'ww_surv_target_2' on a per wastewater unit basis, e.g., 24000",
			title="wastewater surveillance target 2 conc",
		),
		"bs-ww_surv_target_2_conc_unit": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The units of the value specified in 'ww_surv_target_2_conc', e.g., copies/L wastewater",
			title="wastewater surveillance target 2 conc unit",
		),
		"bs-ww_surv_target_2_extract": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Measured amount of surveillance target in the nucleic acid extract that was sequenced; on a per extract unit basis, rather than on a per wastewater sample unit basis, e.g., 12000",
			title="wastewater surveillance target 2 extract",
		),
		"bs-ww_surv_target_2_extract_unit": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The units of the value specified in 'ww_surv_target_2_extract', e.g., copies/microliter extract",
			title="wastewater surveillance target 2 extract unit",
		),
		"bs-ww_surv_target_2_gene": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The name of the gene quantified for the the surveillance target specified in 'ww_surv_target_2', e.g., ORF1-ORF2 junction",
			title="wastewater surveillance target 2 gene",
		),
		"bs-ww_surv_target_2_known_present": Column(
			dtype="object",
			checks=Check.str_matches(r"(?i)(\W|^)(no|yes)(\W|$)"),
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Is genetic material of the surveillance target(s) known to the submitter to be present in this wastewater sample? Presence defined as microbiological evidence of the target organism in the wastewater sample, such as genetic- or culture-based detection.",
			title="wastewater surveillance target 2 known present",
		),
		"bs-ww_surv_target_2_protocol": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="The protocol used to quantify 'ww_surv_target_2'. Specify a reference, website, or brief description.",
			title="wastewater surveillance target 2 protocol",
		),
		"bs-ww_temperature": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Temperature of the wastewater sample at the time of sampling in Celsius, e.g., 25.",
			title="wastewater temperature",
		),
		"bs-ww_total_suspended_solids": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Total concentration of solids in raw wastewater influent sample including a wide variety of material, such as silt, decaying plant and animal matter in milligrams per liter, e.g., 500.",
			title="wastewater total suspended solids",
		),
		"bs-title": Column(
			dtype="object",
			checks=[
				Check(lambda s: s.nunique() == 1),
			],
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Optional internal field for how the BioSample submission should be named when viewed from the NCBI submission portal. If not provided, when performing submissions <--submission_name> with the suffix \"-BS\" will be used instead.",
			title="biosample submission portal name",
		),
		"bs-comment": Column(
			dtype="object",
			checks=[
				Check(lambda s: s.nunique() == 1),
			],
			nullable=True,
			unique=False,
			coerce=False,
			required=False,
			description="Optional internal field explaining the purpose of the submission for when interacting and resolving submission issues with NCBI.",
			title="biosample submission portal description",
		)
	},
	checks=None,
	index=None,
	coerce=False,
	strict="filter",
	name="biosample_package_SARS-CoV-2.wwsurv.1.0_schema",
	ordered=False,
	unique=None,
	report_duplicates="all",
	unique_column_names=True,
	add_missing_columns=False,
	title="BioSample package SARS-CoV-2.wwsurv.1.0 schema",
	description="Schema validation for BioSample database using SARS-CoV-2.wwsurv.1.0 package.",
)