from pandera import DataFrameSchema, Column, Check, Index, MultiIndex

schema = DataFrameSchema(
	columns={
		"Submission_Name": Column(
			dtype="object",
			checks=[
				Check.str_matches(r"^(?!\s*$).+"),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Sample set submission name.",
			title="submission name",
		),
		"Organism": Column(
			dtype="object",
			checks=[
				Check.isin(["FLU", "COV", "POX", "ARBO", "OTHER"]),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Organism submission option.",
			title="organism",
		),
		"Database": Column(
			dtype="object",
			checks=[
				Check.isin(["GENBANK-TBL2ASN", "GENBANK-FTP", "BIOSAMPLE", "SRA", "GISAID"]),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Submitting database name.",
			title="database",
		),
		"Submission_Type": Column(
			dtype="object",
			checks=[
				Check.isin(["TEST", "PRODUCTION"]),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Test/Production",
			title="submission type",
		),
		"Submission_Date": Column(
			dtype="object",
			checks=[
				Check.str_matches(r"^(?!\s*$).+"),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Date submission was started.",
			title="Submission date",
		),
		"Submission_Status": Column(
			dtype="object",
			checks=[
				Check.isin(["SUBMITTED", "CREATED", "QUEUED", "PROCESSING", "FAILED", "PROCESSED", "ERROR", "WAITING", "DELETED", "RETRIED", "EMAILED"]),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Status of current submission.",
			title="submission status",
		),
		"Submission_ID": Column(
			dtype="object",
			checks=[
				Check.str_matches(r'^(PENDING|SUBMITTED|\W*SUB\d+\W*)$'),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="ID for submission group. Submission ID is only for NCBI databases, GISAID will only have 'PENDING' or 'SUBMITTED' if the submission is entirely complete.",
			title="submission id",
		),
		"Submission_Directory": Column(
			dtype="object",
			checks=[
				Check.str_matches(r"^(?!\s*$).+"),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Directory of submission files.",
			title="submission directory",
		),
		"Config_File": Column(
			dtype="object",
			checks=[
				Check.str_matches(r"^(?!\s*$).+"),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Config file used to make submission.",
			title="config file",
		),
		"Update_Date": Column(
			dtype="object",
			checks=[
				Check.str_matches(r"^(?!\s*$).+"),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Date submission was last updated.",
			title="update date",
		),
	},
     checks=None,
     index=None,
     coerce=False,
     strict=True,
     name="seqsender_log_schema",
     ordered=False,
     unique=None,
     report_duplicates="all",
     unique_column_names=True,
     add_missing_columns=False,
     title="seqsender log schema",
     description="Schema validation for seqsender submission log.",
)
