from pandera import DataFrameSchema, Column, Check, Index, MultiIndex

schema = DataFrameSchema(
	columns={
		"bs-sample_name": Column(
			dtype="object",
			checks=[
				Check.str_matches(r"^(?!\s*$).+"),
				Check.str_length(max_value=50),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Sample name used for BioSample submission.",
			title="biosample sample name",
		),
		"biosample_status": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=True,
			description="Current status of the BioSample submission.",
			title="biosample sample submission status",
		),
		"biosample_accession": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=True,
			description="Sample accession ID used to identify BioSample submission NCBI.",
			title="biosample sample submission accession",
		),
		"biosample_message": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=True,
			description="If there is a message tied to the sample submitted to BioSample, it will appear here.",
			title="biosample sample submission message",
		),
	},
     checks=None,
     index=None,
     coerce=False,
     strict="filter",
     name="seqsender_status_report_biosample_schema",
     ordered=True,
     unique=None,
     report_duplicates="all",
     unique_column_names=True,
     add_missing_columns=False,
     title="seqsender status report biosample schema",
     description="Schema validation for seqsender status report files to prevent incorrect linking of BioSample accessions.",
)
