from pandera import DataFrameSchema, Column, Check, Index, MultiIndex

schema = DataFrameSchema(
	columns={
		"gb-sample_name": Column(
			dtype="object",
			checks=[
				Check.str_matches(r"^(?!\s*$).+"),
				Check.str_length(max_value=50),
			],
			nullable=False,
			unique=True,
			coerce=False,
			required=True,
			description="Sample name used for GenBank submission.",
			title="genbank sample name",
		),
		"genbank_status": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=True,
			description="Current status of the GenBank submission.",
			title="genbank sample submission status",
		),
		"genbank_accession": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=True,
			description="Sample accession ID used to identify GenBank submission NCBI.",
			title="genbank sample submission accession",
		),
		"genbank_message": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=True,
			description="If there is a message tied to the sequence submitted to GenBank, it will appear here.",
			title="genbank sample submission message",
		),
	},
     checks=None,
     index=None,
     coerce=False,
     strict="filter",
     name="seqsender_status_report_genbank_schema",
     ordered=True,
     unique=None,
     report_duplicates="all",
     unique_column_names=True,
     add_missing_columns=False,
     title="seqsender status report genbank schema",
     description="Schema validation for seqsender status report files to prevent incorrect linking of GenBank accessions.",
)
