from pandera import DataFrameSchema, Column, Check, Index, MultiIndex

schema = DataFrameSchema(
	columns={
		"sra-sample_name": Column(
			dtype="object",
			checks=[
				Check.str_matches(r"^(?!\s*$).+"),
				Check.str_length(max_value=50),
			],
			nullable=False,
			unique=False,
			coerce=False,
			required=True,
			description="Sample name used for SRA submission.",
			title="sra sample name",
		),
		"sra_status": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=True,
			description="Current status of the SRA submission.",
			title="sra sample submission status",
		),
		"sra_accession": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=True,
			description="Sample accession ID used to identify SRA submission NCBI.",
			title="sra sample submission accession",
		),
		"sra_message": Column(
			dtype="object",
			checks=None,
			nullable=True,
			unique=False,
			coerce=False,
			required=True,
			description="If there is a message tied to the sequence submitted to SRA, it will appear here.",
			title="sra sample submission message",
		),
	},
     checks=None,
     index=None,
     coerce=False,
     strict="filter",
     name="seqsender_status_report_sra_schema",
     ordered=True,
     unique=None,
     report_duplicates="all",
     unique_column_names=True,
     add_missing_columns=False,
     title="seqsender status report sra schema",
     description="Schema validation for seqsender status report files to prevent incorrect linking of SRA accessions.",
)
